#!/bin/bash

######################################  INFO  ####################################
#
# Provides:		Spaceship
# Required-Start: 	$smbus
# Required-Stop: 	$smbus
# Default-Start: 	2 3 4 5
# Default-Stop: 	0 1 6
# Short-Description: 	Control de una nave espacial.
# Description:		Con el uso de un giroscopio se puede controlar una nave
#			espacial que se puede visualizar en una matriz de leds
#
##################################################################################

#Se define donde se encuentra nuestro programa que queremos que corra desde un inicio
DIR=/usr/lib/python2.7/site-packages
#Nuestro demonio se llama igual que nuestro programa prueba_01 y queremos que corra con privilegios de root
DAEMON=$DIR/prueba_01.py
DAEMON_NAME=prueba_01
DAEMON_USER=root
#En esta ruta se encuentra el pid de la aplicacion, que servira para poder manipularla.
PIDFILE=/var/run/$DAEMON_NAME.pid
PID=$(cat $PIDFILE)
#Start-stop-daemon son comando para la manipulacion de demonios
do_start() {
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON 
	}

do_stop() {
	start-stop-daemon --stop --background --pidfile $PIDFILE --retry 10
	}
#3 casos start, stop y status
case "$1" in 
	start) 
		if [ ! -z $PID ] ; then
			if [ -d /proc/$PID ] ; then 
				echo "Error: El proceso ($PID) ya existe"
				exit 1
			fi
		fi
		echo "Levantando el demonio $DAEMON_NAME..."
		#en el caso de start se le da tiempo al sistema para que todos los componentes inicien
		#modprobe 12c-dev nos permite inicializar la comuniacion i2c
			sleep 15
			modprobe i2c-dev
			do_start
	;;
	stop) 
		if [ -d /proc/$PID ] ; then
			echo "Deteniendo demonio $DAEMON_NAME ($PID)"
			do_stop
		else
			"El demonio $PID ya no esta corriendo"
			exit 0
		fi
		sleep 1 
		if [ -d /proc/$PID ] ; then 
			echo "El demonio $DAEMON_NAME ($PID) sigue corriendo"
			echo "Habra que cortarle las piernas"
			kill -KILL $PID
		fi
	;;

	status)
		if [ -d /proc/$PID ] ; then 
			echo "$DAEMON_NAME ($PID) corrienndo"
		fi
	;;

	*)
		echo "Usando: /etc/init.d/$DAEMON_NAME {start|stop|status}"
	;;

esac
exit 0 
